{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- include "jitsi-meet.prometheus.fullname" . | nindent 4 }}-conf
  labels:
    name: {{- include "jitsi-meet.prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: | 
    scrape_configs:
	{{- range $shardName, $shardConfig := .Values.global.shards }}
    {{- $fullShardName := include "jitsi-meet.fullShardName" (dict "root" $ "shardName" $shardName) -}}
    {{- with $ }}
    {{- $maxReplicas := .Values.jvb.replicaCount -}}
    {{- if .Values.jvb.autoscaling.enabled }}
    {{- $maxReplicas = .Values.jvb.autoscaling.maxReplicas -}}
    {{- end }}
    {{- range $replica := (untilStep 0 (int $maxReplicas) 1) }}
    {{- with $ }}
    - job_name: 'jvb{{ $replica }}-exporter'
      scrape_interval: 1m
      scrape_timeout: 1m
      static_configs:
      - targets: ['{{ $fullShardName }}-jvb-ws-{{ $replica }}.default.svc.cluster.local:9888']
	{{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
