{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{- include "jitsi-meet.prometheus.fullname" . | nindent 4 }}
  labels:
    name: {{- include "jitsi-meet.prometheus.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    protocol: TCP
    name: prometheus
  selector:
    {{- include "jitsi-meet.prometheus.selectorLabels" . | nindent 4 }}
{{- end }}
