apiVersion: apps/v1
kind: Deployment
metadata:
  name: litho-sre-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  litho-sre-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litho-sre-prometheus
        name: litho-sre-prometheus
    spec:
      containers:
      - name:  litho-sre-prometheus
        image: bitnami/prometheus:latest
        ports:
          - containerPort: 9090
        volumeMounts:
            - name: litho-sre-prometheus-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: litho-sre-prometheus-volume
          configMap: 
            defaultMode: 420
            name: litho-sre-prometheus-conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: litho-sre-prometheus-conf
  labels:
    name: litho-sre-prometheus-conf
data:
  prometheus.yml: | 
    scrape_configs:
    - job_name: 'jvb0-exporter'
      scrape_interval: 1m
      scrape_timeout: 1m
      static_configs:
      - targets: ['myjitsi-jitsi-meet-shard-0-jvb-ws-0.default.svc.cluster.local:9888']
    - job_name: 'jvb1-exporter'
      scrape_interval: 1m
      scrape_timeout: 1m
      static_configs:
      - targets: ['myjitsi-jitsi-meet-shard-0-jvb-ws-1.default.svc.cluster.local:9888']
---

apiVersion: v1
kind: Service
metadata:
  name: litho-sre-prometheus-svc
  labels:
    name: litho-sre-prometheus-svc
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app.kubernetes.io/name: litho-sre-prometheus
  sessionAffinity: None
status:
  loadBalancer: {}

