FROM jitsi/web:stable-7648-4

COPY watermark.svg /usr/share/jitsi-meet/images/watermark.svg
COPY main.json /usr/share/jitsi-meet/lang/main.json
COPY app.bundle.min.js /usr/share/jitsi-meet/libs/app.bundle.min.js
COPY title.html /usr/share/jitsi-meet/title.html
COPY ttttlogo.png /usr/share/jitsi-meet/images/ttttlogo.png
COPY favicon.ico /usr/share/jitsi-meet/images/favicon.ico
COPY manifest.json /usr/share/jitsi-meet/manifest.json
COPY interface_config.js /defaults/interface_config.js
