apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: c3d835a55edbabcefcd0fcb562ca00cc477bcea7e29da75cb4d832b25e01899e
    checksum/privateconfig: 9b97cd982b7c58c071fd3b6a673907d01a55539f313101e09fe23141fbd0b37c
    checksum/secret: a512de50e7be5fc1417dbfaf8bdcb81e67bb5a16c0f9143ca3e606f25b08a966
  creationTimestamp: "2022-10-05T15:13:05Z"
  generateName: easyjitsi-shard-0-jvb-
  labels:
    app.kubernetes.io/instance: easyjitsi
    app.kubernetes.io/name: jitsi
    controller-revision-hash: easyjitsi-shard-0-jvb-769c44b499
    jitsi/component: jvb
    jitsi/shard: shard-0
    statefulset.kubernetes.io/pod-name: easyjitsi-shard-0-jvb-0
  name: easyjitsi-shard-0-jvb-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: easyjitsi-shard-0-jvb
    uid: 29c4ebd3-41bf-4bc3-b864-9fd94a2dc15d
  resourceVersion: "39662"
  uid: a54c1a05-6165-4de8-935d-397eef02cf5e
spec:
  containers:
  - args:
    - /init
    command:
    - /entrypoint/entrypoint.sh
    env:
    - name: BASE_PORT
      value: "30000"
    - name: JVB_WS_SERVER_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: DOCKER_HOST_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: XMPP_SERVER
      value: easyjitsi-shard-0-prosody
    - name: XMPP_AUTH_DOMAIN
      valueFrom:
        configMapKeyRef:
          key: XMPP_AUTH_DOMAIN
          name: easyjitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      valueFrom:
        configMapKeyRef:
          key: XMPP_INTERNAL_MUC_DOMAIN
          name: easyjitsi
    - name: ENABLE_COLIBRI_WEBSOCKET
      valueFrom:
        configMapKeyRef:
          key: ENABLE_COLIBRI_WEBSOCKET
          name: easyjitsi
    - name: JVB_AUTH_USER
      valueFrom:
        configMapKeyRef:
          key: JVB_AUTH_USER
          name: easyjitsi
    - name: JVB_BREWERY_MUC
      valueFrom:
        configMapKeyRef:
          key: JVB_BREWERY_MUC
          name: easyjitsi
    - name: JVB_ENABLE_APIS
      valueFrom:
        configMapKeyRef:
          key: JVB_ENABLE_APIS
          name: easyjitsi
    - name: JVB_WS_DOMAIN
      valueFrom:
        configMapKeyRef:
          key: JVB_WS_DOMAIN
          name: easyjitsi
    - name: PUBLIC_URL
      valueFrom:
        configMapKeyRef:
          key: PUBLIC_URL
          name: easyjitsi
    - name: TZ
      valueFrom:
        configMapKeyRef:
          key: TZ
          name: easyjitsi
    - name: JVB_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: JVB_AUTH_PASSWORD
          name: easyjitsi
    - name: JVB_STUN_SERVERS
      valueFrom:
        secretKeyRef:
          key: JVB_STUN_SERVERS
          name: easyjitsi
    image: jitsi/jvb:stable-7648-4
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - bash
          - /shutdown/graceful_shutdown.sh
          - -t 3
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /about/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: jitsi
    ports:
    - containerPort: 9090
      name: http
      protocol: TCP
    - containerPort: 8080
      name: admin
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /about/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /entrypoint/entrypoint.sh
      name: jvb
      subPath: entrypoint.sh
    - mountPath: /shutdown/graceful_shutdown.sh
      name: jvb
      subPath: graceful_shutdown.sh
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h72np
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: easyjitsi-shard-0-jvb-0
  nodeName: gke-cluster-1-default-pool-dd243b79-tl7b
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: easyjitsi-shard-0-jvb
  terminationGracePeriodSeconds: 3600
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: entrypoint.sh
        mode: 484
        path: entrypoint.sh
      - key: graceful_shutdown.sh
        mode: 484
        path: graceful_shutdown.sh
      name: easyjitsi-jvb
    name: jvb
  - name: kube-api-access-h72np
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-10-05T15:13:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-10-05T15:13:05Z"
    message: 'containers with unready status: [jitsi]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-10-05T15:13:05Z"
    message: 'containers with unready status: [jitsi]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-10-05T15:13:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://317925950503d18998edde2e38ff3d3f9f19042a11eb4510fe215a2aadb56179
    image: docker.io/jitsi/jvb:stable-7648-4
    imageID: docker.io/jitsi/jvb@sha256:59f8f94e158f7b4cb04a68963295e5ac1e1ef981506e6a393fca95567423c431
    lastState:
      terminated:
        containerID: containerd://7f9d8820a51963b716b84b001eaad0bc15cb4b83a64b119c56dd2a357cda5bfc
        exitCode: 0
        finishedAt: "2022-10-05T15:13:50Z"
        reason: Completed
        startedAt: "2022-10-05T15:13:12Z"
    name: jitsi
    ready: false
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2022-10-05T15:13:52Z"
  hostIP: 10.128.0.4
  phase: Running
  podIP: 10.4.2.12
  podIPs:
  - ip: 10.4.2.12
  qosClass: BestEffort
  startTime: "2022-10-05T15:13:05Z"
