apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: easyjitsi
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-10-05T15:13:05Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: easyjitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi
    app.kubernetes.io/version: stable-7648-4
    helm.sh/chart: jitsi-0.1.0
    jitsi/component: jvb
    jitsi/shard: shard-0
  name: easyjitsi-shard-0-jvb
  namespace: default
  resourceVersion: "39207"
  uid: 29c4ebd3-41bf-4bc3-b864-9fd94a2dc15d
spec:
  podManagementPolicy: Parallel
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: easyjitsi
      app.kubernetes.io/name: jitsi
      jitsi/component: jvb
      jitsi/shard: shard-0
  serviceName: easyjitsi-shard-0-jvb
  template:
    metadata:
      annotations:
        checksum/config: c3d835a55edbabcefcd0fcb562ca00cc477bcea7e29da75cb4d832b25e01899e
        checksum/privateconfig: 9b97cd982b7c58c071fd3b6a673907d01a55539f313101e09fe23141fbd0b37c
        checksum/secret: a512de50e7be5fc1417dbfaf8bdcb81e67bb5a16c0f9143ca3e606f25b08a966
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: easyjitsi
        app.kubernetes.io/name: jitsi
        jitsi/component: jvb
        jitsi/shard: shard-0
    spec:
      containers:
      - args:
        - /init
        command:
        - /entrypoint/entrypoint.sh
        env:
        - name: BASE_PORT
          value: "30000"
        - name: JVB_WS_SERVER_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: DOCKER_HOST_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: XMPP_SERVER
          value: easyjitsi-shard-0-prosody
        - name: XMPP_AUTH_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: XMPP_AUTH_DOMAIN
              name: easyjitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: XMPP_INTERNAL_MUC_DOMAIN
              name: easyjitsi
        - name: ENABLE_COLIBRI_WEBSOCKET
          valueFrom:
            configMapKeyRef:
              key: ENABLE_COLIBRI_WEBSOCKET
              name: easyjitsi
        - name: JVB_AUTH_USER
          valueFrom:
            configMapKeyRef:
              key: JVB_AUTH_USER
              name: easyjitsi
        - name: JVB_BREWERY_MUC
          valueFrom:
            configMapKeyRef:
              key: JVB_BREWERY_MUC
              name: easyjitsi
        - name: JVB_ENABLE_APIS
          valueFrom:
            configMapKeyRef:
              key: JVB_ENABLE_APIS
              name: easyjitsi
        - name: JVB_WS_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: JVB_WS_DOMAIN
              name: easyjitsi
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              key: PUBLIC_URL
              name: easyjitsi
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: easyjitsi
        - name: JVB_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: JVB_AUTH_PASSWORD
              name: easyjitsi
        - name: JVB_STUN_SERVERS
          valueFrom:
            secretKeyRef:
              key: JVB_STUN_SERVERS
              name: easyjitsi
        image: jitsi/jvb:stable-7648-4
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - /shutdown/graceful_shutdown.sh
              - -t 3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /about/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: jitsi
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /about/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /entrypoint/entrypoint.sh
          name: jvb
          subPath: entrypoint.sh
        - mountPath: /shutdown/graceful_shutdown.sh
          name: jvb
          subPath: graceful_shutdown.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3600
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: entrypoint.sh
            mode: 484
            path: entrypoint.sh
          - key: graceful_shutdown.sh
            mode: 484
            path: graceful_shutdown.sh
          name: easyjitsi-jvb
        name: jvb
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 5
  currentRevision: easyjitsi-shard-0-jvb-769c44b499
  observedGeneration: 1
  replicas: 5
  updateRevision: easyjitsi-shard-0-jvb-769c44b499
  updatedReplicas: 5
