{{- $serverID := default "podIP" .Values.jvb.websockets.serverID }}
{{- range $shardName, $shardConfig := .Values.global.shards }}
{{- $fullShardName := include "jitsi-meet.fullShardName" (dict "root" $ "shardName" $shardName) -}}
{{- with $ }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
    {{- with .Values.jvb.annotations }}
      annotations:
        {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $fullShardName }}-jvb
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 6 }}
      jitsi/component: jvb
      jitsi/shard: "{{ $shardName }}"
  serviceName: {{ $fullShardName }}-jvb
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/jvb/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/jvb/xmpp-secret.yaml") . | sha256sum }}
      labels:
        {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 8 }}
        {{- range $label, $value := mergeOverwrite .Values.global.podLabels .Values.jvb.podLabels }}
          {{ $label }}: {{ $value }}
        {{- end }}
        jitsi/shard: "{{ $shardName }}"
        jitsi/component: jvb
    spec:
      containers:
      - args:
        - /init
        command:
        - /entrypoint/entrypoint.sh
        envFrom:
        - secretRef:
            name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jvb
        - configMapRef:
            name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-common
        - configMapRef:
            name: {{ include "jitsi-meet.jvb.fullname" . }}
        env:
        - name: BASE_PORT
          value: {{ $shardConfig.jvbBasePort | quote }}
        {{- if or .Values.jvb.useNodeIP .Values.jvb.publicIP }}
        - name: DOCKER_HOST_ADDRESS
          {{- if .Values.jvb.publicIP }}
          value: {{ .Values.jvb.publicIP }}
          {{- else }}
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          {{- end }}
        {{- end }}
        {{- if .Values.jvb.websockets.enabled }}
        - name: JVB_WS_SERVER_ID
          {{- if eq $serverID "service" }}
          value: {{ include "jitsi-meet.jvb.fullname" . }}.{{ .Release.Namespace }}.svc
          {{- else if eq $serverID "podIP" }}
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
          {{- else }}
          value: {{ $serverID | quote }}
          {{- end }}
        {{- end }}
        {{- if  .Values.octo.enabled }}
        - name: JVB_OCTO_BIND_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JVB_OCTO_PUBLIC_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- end }}
        image: "{{ .Values.jvb.image.repository }}:{{ default .Chart.AppVersion .Values.jvb.image.tag }}"
        imagePullPolicy: {{ pluck "pullPolicy" .Values.jvb.image .Values.image | first }}
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - /shutdown/graceful_shutdown.sh
              - -t 3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /about/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: jitsi
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /about/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.jvb.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /entrypoint/entrypoint.sh
          name: jvb
          subPath: entrypoint.sh
          
        - mountPath: /shutdown/graceful_shutdown.sh
          name: jvb
          subPath: graceful_shutdown.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3600
      volumes:
        - name: jvb
          configMap:
            name: {{ include "jitsi-meet.fullname" . }}-jvb
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
                mode: 0744
              - key: graceful_shutdown.sh
                path: graceful_shutdown.sh
                mode: 0744
              {{- range .Values.jvb.extraFiles }}
              - key: {{ .name }}
                path: {{ .name }}
                mode: {{ .mode | default "0400" }}
              {{- end }}
  updateStrategy:
    type: RollingUpdate
{{- end }}
{{- end }}
