apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jicofo
  name: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jicofo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: jicofo
    spec:
      containers:
        - env:
            - name: JICOFO_AUTH_PASSWORD
              value: 32e328161cf3d75432a1c59dccd09fbf
            - name: SENTRY_DSN
              value: '"0"'
            - name: TZ
              value: UTC
            - name: XMPP_SERVER
              value: prosody
          image: jitsi/jicofo:stable-7648-4
          name: jicofo
          resources: {}
      restartPolicy: Always
status: {}
