apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: prosody
  name: prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prosody
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: prosody
    spec:
      containers:
        - env:
            - name: JIBRI_RECORDER_PASSWORD
              value: 21e3dd5405c1bddbdf697e9ec4522aff
            - name: JIBRI_XMPP_PASSWORD
              value: db5c296067472c3b6b12f862ce5138ef
            - name: JICOFO_AUTH_PASSWORD
              value: 32e328161cf3d75432a1c59dccd09fbf
            - name: JIGASI_XMPP_PASSWORD
              value: 2c5063250bce331ccabaa739d3d1d6be
            - name: JVB_AUTH_PASSWORD
              value: 651a16c7b4828bb69ec8d7acbc9fb2af
            - name: PUBLIC_URL
              value: https://35.225.153.210
            - name: TZ
              value: UTC
          image: jitsi/prosody:stable-7648-4
          name: prosody
          ports:
            - containerPort: 5222
            - containerPort: 5347
            - containerPort: 5280
          resources: {}
      restartPolicy: Always
status: {}
