apiVersion: v1
kind: Service
metadata:
  name: jvb-udp
  labels:
spec:
  type: LoadBalancer
  ports:
    - name: jvb0
      port: 30000
      #nodePort: 30000
      protocol: UDP
      targetPort: rtp-udp
    - name: jvb1
      port: 30001
      targetPort: rtp-udp-30001
        #nodePort: 30001
      protocol: UDP
    - name: jvb2
      port: 30002
      targetPort: rtp-udp-30002
        #nodePort: 30002
      protocol: UDP
  selector:
    app.service: jvb
