apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jvb2
  labels:
    {{- include "jitsi-meet.jvb2.labels" . | nindent 4 }}
type: Opaque
data:
  JVB_AUTH_USER: '{{ .Values.jvb2.xmpp.user | b64enc }}'
  JVB_AUTH_PASSWORD: '{{ default (randAlphaNum 10) .Values.jvb.xmpp.password | b64enc }}'
