apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable-7001 #5076 working one
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: "prosody.jitsi.svc.cluster.local"
            - name: XMPP_DOMAIN
              value: "jitsi.dennychen.tw"
            - name: XMPP_AUTH_DOMAIN
              value: "auth.jitsi.dennychen.tw"
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: "internal-muc.jitsi.dennychen.tw"
            - name: JICOFO_COMPONENT_SECRET
              value: "abscdees"
            - name: JICOFO_AUTH_USER
              value: "focus"
            - name: JICOFO_AUTH_PASSWORD
              value: "adaad134"
            - name: TZ
              value: "UTC"
            - name: JVB_BREWERY_MUC
              value: "jvbbrewery"
            - name: ENABLE_RECORDING
              value: "1"
            - name: JIBRI_BREWERY_MUC
              value: "jibribrewery"
            - name: JIBRI_RECORDER_PASSWORD
              value: "aDAGafa141afafa"
            - name: JIBRI_XMPP_USER
              value: "jibri"
            - name: JIBRI_XMPP_PASSWORD
              value: "Asababfa13AD"
            - name: JIBRI_RECORDER_USER
              value: "recorder"
            - name: JIBRI_PENDING_TIMEOUT
              value: "0"
            - name: JICOFO_ENABLE_HEALTH_CHECKS
              value: "true"
            - name: XMPP_MUC_DOMAIN
              value: "muc.jitsi.dennychen.tw"
            - name: ENABLE_XMPP_WEBSOCKET
              value: "1"
            - name: XMPP_RECORDER_DOMAIN
              value: "recorder.jitsi.dennychen.tw"
