apiVersion: cert-manager.io/v1
kind: Issuer
metadata: 
  name: web
  namespace: jitsi
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your_email@domain.tld
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
