apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      containers:
        - name: jvb
          ports:
          - containerPort: 30300
            protocol: UDP
          - containerPort: 9090        
          image: jitsi/jvb:stable-7001
          resources: 
            limits:
               memory: "2G"
               cpu: "2"
            requests:
               memory: "1G"
               cpu: "1"
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLE_XMPP_WEBSOCKET
              value: "1"
            - name: ENABLE_COLIBRI_WEBSOCKET
              value: "1"
            - name: PUBLIC_URL
              value: "https://jitsi.dennychen.tw"
            - name: JVB_ENABLE_APIS
              value: "rest,colibri"
            - name: COLIBRI_REST_ENABLED
              value: "true"
            - name: XMPP_SERVER
              value: "prosody.jitsi.svc.cluster.local"
            - name: DOCKER_HOST_ADDRESS
              value: "192.168.1.1"
            - name: XMPP_DOMAIN
              value: "jitsi.dennychen.tw"
            - name: XMPP_AUTH_DOMAIN
              value: "auth.jitsi.dennychen.tw"
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: "internal-muc.jitsi.dennychen.tw"
            - name: JVB_STUN_SERVERS
              value: "stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302"
            - name: JICOFO_AUTH_USER
              value: "focus"
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: "jvb"
            - name: JVB_PORT
              value: "30300"
            - name: JVB_AUTH_PASSWORD
              value: "afa13ada"
            - name: JICOFO_AUTH_PASSWORD
              value: "adaad134"
            - name: JVB_BREWERY_MUC
              value: "jvbbrewery"
            - name: TZ
              value: "UTC"
            - name: XMPP_MUC_DOMAIN
              value: "muc.jitsi.dennychen.tw"
