apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - name: prosody
          image: jitsi/prosody:stable-7001
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5222
          - containerPort: 5280
          - containerPort: 5347
          - containerPort: 5269
          env:
            - name: ENABLE_XMPP_WEBSOCKET # added
              value: "1"
            - name: XMPP_DOMAIN
              value: "jitsi.dennychen.tw"   
            - name: LOG_LEVEL
              value: "debug"              
            - name: XMPP_AUTH_DOMAIN
              value: "jitsi.dennychen.tw"
            - name: XMPP_MUC_DOMAIN
              value: "jitsi.dennychen.tw"
            - name: XMPP_MUC_MODULES
              value: "muc_meeting_id,muc_domain_mapper"
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: "internal-muc.jitsi.dennychen.tw"
            - name: JICOFO_COMPONENT_SECRET
              value: "abscdees"
            - name: JVB_AUTH_USER
              value: "jvb"
            - name: JVB_AUTH_PASSWORD
              value: "afa13ada"
            - name: JICOFO_AUTH_USER
              value: "focus"
            - name: JICOFO_AUTH_PASSWORD
              value: "adaad134"
            - name: TZ
              value: "UTC"
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: XMPP_TRUST_ALL_CERTS
              value: "true"
            - name: JIBRI_XMPP_USER
              value: "jibri"
            - name: JIBRI_XMPP_PASSWORD
              value: "Asababfa13AD"
            - name: JIBRI_BREWERY_MUC
              value: "jibribrewery"
            - name: JIBRI_RECORDER_USER
              value: "recorder"
            - name: JIBRI_RECORDER_PASSWORD
              value: "aDAGafa141afafa"
            - name: ENABLE_RECORDING
              value: "1"
            - name: JIBRI_USAGE_TIMEOUT
              value: "0"
            - name: ENABLE_LOBBY
              value: "0"
            - name: ENABLE_GUEST
              value: "1"
            - name: PUBLIC_URL
              value: "https://jitsi.dennychen.tw"
            - name: XMPP_RECORDER_DOMAIN
              value: "recorder.jitsi.dennychen.tw"
            - name: XMPP_CROSS_DOMAIN
              value: "true"
            - name: XMPP_GUEST_DOMAIN
              value: "guest.jitsi.dennychen.tw"
            - name: JIBRI_STRIP_DOMAIN_JID
              value: "muc"
