apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-web
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jitsi-web
  template:
    metadata:
      labels:
        app: jitsi-web
    spec:
      containers:
        - name: jitsi-web
          ports:
          - containerPort: 80
          - containerPort: 443
          image: jitsi/web:stable-7001
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLE_XMPP_WEBSOCKET # added
              value: "1"
            - name: ENABLE_COLIBRI_WEBSOCKET
              value: "1"
            - name: DEPLOYMENTINFO_ENVIRONMENT
              value: "jitsi.dennychen.tw"
            - name: DEPLOYMENTINFO_ENVIRONMENT_TYPE
              value: "prod"
            - name: DEPLOYMENTINFO_REGION
              value: "Asia-central-1"
            - name: DEPLOYMENTINFO_SHARD
              value: "asia-central"
            - name: DEPLOYMENTINFO_USERREGION
              value: "Asia-central-1"
            - name: PUBLIC_URL # added
              value: "https://jitsi.dennychen.tw"
            - name: XMPP_SERVER
              value: "prosody.jitsi.svc.cluster.local"
            - name: JICOFO_AUTH_USER
              value: "focus"
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: XMPP_DOMAIN
              value: "jitsi.dennychen.tw"
            - name: XMPP_AUTH_DOMAIN
              value: "auth.jitsi.dennychen.tw"
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: "internal-muc.jitsi.dennychen.tw"
            - name: XMPP_BOSH_URL_BASE
              value: "http://prosody.jitsi.svc.cluster.local:5280"
            - name: XMPP_MUC_DOMAIN
              value: "muc.jitsi.dennychen.tw"
            - name: TZ
              value: "UTC"
            - name: DISABLE_HTTPS
              value: "1"
            - name: DOCKER_HOST_ADDRESS
              value: "192.168.1.1"
            - name: ENABLE_GUESTS
              value: "1"
            - name: XMPP_GUEST_DOMAIN
              value: "guest.jitsi.dennychen.tw"
            - name: DISABLE_AUDIO_LEVELS
              value: "0"
            - name: XMPP_RECORDER_DOMAIN
              value: "recorder.jitsi.dennychen.tw"
            - name: JIBRI_XMPP_USER
              value: "jibri"
            - name: JIBRI_XMPP_PASSWORD
              value: "Asababfa13AD"
            - name: JIBRI_BREWERY_MUC
              value: "jibribrewery"
            - name: JIBRI_RECORDER_USER
              value: "recorder"
            - name: JIBRI_RECORDER_PASSWORD
              value: "aDAGafa141afafa"
            - name: JIBRI_RECORDING_DIR
              value: "/config/recordings"
            - name: JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
              value: "/config/finalize.sh"
            - name: JIBRI_STRIP_DOMAIN_JID
              value: "muc" # muc or conference
            - name: JIBRI_LOGS_DIR
              value: "/config/logs"
            - name: ENABLE_RECORDING
              value: "1"
            - name: ENABLE_WELCOME_PAGE
              value: "1"
            - name: ENABLE_CLOSE_PAGE
              value: "1"
            - name: ENABLE_P2P
              value: "0"
#            - name: ENABLE_NO_AUDIO_DETECTION
#              value: "1"
#            - name: ENABLE_NOISY_MIC_DETECTION
#              value: "1"
            - name: ENABLE_STATS_ID
              value: "1"
            - name: JIBRI_PENDING_TIMEOUT
              value: "0"
            - name: WEBSOCKET_KEEP_ALIVE
              value: "0"
            - name: ENABLE_PREJOIN_PAGE
              value: "0"
